### ISSUE TITLE
Try to host the website on local server as before it was hosted

### ISSUE THREAD

**Issue by sheshant1** [p-society/Online_Rosie_FrontEnd#9]
Please try to host this website on the local machine as it was before because the loading or booting time of website on slow net is about half an hour. If you will host the website on local server people in the campus can easily book the mess coupon in very sort period of time. I am not telling you to change the database location. Just change the `html and it's supporting file and script` to local server and put a `cross origin` header on the main server. If not possible then we hope for a best solution.

**Comment by palash25** [comment]
Easier said than done.

> Please try to host this website on the local machine

the local servers use windows 2002 OS which was causing a lot of problems with regards to dependencies.

> booting time of website on slow net is about half an hour.

it only happens when you load it for the first time ever, subsequent attempts to load the site will take lesser time.

Also the site is hosted on a free glitch server, we had requested the director for some funds to get a premium hosting so that we can get faster load times, but the administration doesn't seem to care about it and the DIrector's solution was that we can pay for it out of our own pocket.

> If not possible then we hope

so I guess this is not possible for now

Anyway thanks for raising the issue :smile:

**Comment by arijeetsat** [comment]
If we can't get a completely new domain, at least a sub-domain is possible, the mess secretary will be pitching in the proposal for the sub-domain.

**Comment by palash25** [comment]
> If we can't get a completely new domain, at least a sub-domain is possible

We are not talking about the domain here
